# -*- coding: utf-8 -*-
"""FOIL-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ds4SHWLmpxh0LPW3nciWjLNBHlOnLUGX
"""



"""# Task
The task is to load a publicly available classification dataset, preprocess it, generate propositional classification rules using a `DecisionTreeClassifier`, and then provide a conceptual explanation of the FOIL (First-Order Inductive Learner) algorithm, summarizing the process and presenting the generated rules.

## Load Public Dataset

### Subtask:
Select a publicly available dataset suitable for classification tasks (e.g., Iris, Breast Cancer Wisconsin) and load it into a pandas DataFrame. The dataset should be simple enough to facilitate rule extraction and conceptual explanation.

**Reasoning**:
To load the Iris dataset, convert it into a pandas DataFrame, and inspect its initial structure and data types, I will use `sklearn.datasets.load_iris` and then `pandas.DataFrame`, followed by `df.head()` and `df.info()`.
"""

import pandas as pd
from sklearn.datasets import load_iris

# 1. Load the Iris dataset
iris = load_iris()

# 2. Create a pandas DataFrame from the data and target components
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target

# 3. Display the first few rows of the DataFrame and its information
print("First 5 rows of the Iris DataFrame:")
print(df.head())
print("\nInformation about the Iris DataFrame:")
df.info()

"""## Preprocess Data

### Subtask:
Preprocess the selected dataset. This will include handling any missing values, encoding categorical features if present, and splitting the data into training and testing sets for model evaluation.

**Reasoning**:
To preprocess the dataset as instructed, I will first separate the features (X) from the target variable (y) and then split the data into training and testing sets using `train_test_split` from `sklearn.model_selection`.
"""

from sklearn.model_selection import train_test_split

# Separate features (X) and target (y)
X = df.drop('target', axis=1)
y = df['target']

# Split the data into training and testing sets (80/20 ratio)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

"""## Generate Propositional Rules

### Subtask:
Generate propositional classification rules using a DecisionTreeClassifier and present them in a readable format.

**Reasoning**:
To generate and present the propositional classification rules, I will import the necessary modules, instantiate a DecisionTreeClassifier with specified parameters, train it on the prepared training data, and then use export_text to display the rules in a readable format.
"""

from sklearn.tree import DecisionTreeClassifier, export_text

# 1. Instantiate a DecisionTreeClassifier
# Set max_depth to control complexity and random_state for reproducibility
dtc = DecisionTreeClassifier(max_depth=4, random_state=42)

# 2. Train the DecisionTreeClassifier
dtc.fit(X_train, y_train)

# 3. Extract and print the rules
feature_names = X.columns.tolist()
rules = export_text(dtc, feature_names=feature_names)
print("Generated Propositional Rules:")
print(rules)

"""## Conceptual FOIL Application

### Subtask:
Explain the concept of the FOIL (First-Order Inductive Learner) algorithm. This step will focus on a conceptual overview of how FOIL learns first-order rules, its differences from propositional rule learning, and its application in relational domains.

## Conceptual FOIL Application

### Subtask:
Explain the concept of the FOIL (First-Order Inductive Learner) algorithm. This step will focus on a conceptual overview of how FOIL learns first-order rules, its differences from propositional rule learning, and its application in relational domains.

### Explanation of FOIL (First-Order Inductive Learner)

#### 1. What is FOIL?
FOIL (First-Order Inductive Learner) is a classical algorithm in relational learning, a subfield of machine learning that deals with data where instances are not independent and identically distributed, but rather are related to each other. Specifically, FOIL is designed to induce first-order logical rules from data, meaning it learns rules expressed in terms of predicates and variables, capable of capturing relationships between multiple entities. Unlike propositional learners that operate on flat, attribute-value tables, FOIL excels in domains where data is rich in structure and relationships.

#### 2. Core Idea: Greedy, Top-Down Rule Induction
FOIL employs a greedy, top-down approach to rule induction. It works by iteratively learning a set of first-order rules that cover positive examples while excluding negative ones. The process for learning a single rule can be summarized as follows:

*   **Initialization**: Start with a very general rule (e.g., `P(X, Y) :- True`), which covers many positive and negative examples.
*   **Refinement**: Iteratively add new literals (conditions) to the rule's body. Each literal restricts the rule, making it more specific and reducing the number of negative examples it covers.
*   **Literal Selection**: At each step, FOIL evaluates potential literals (e.g., `Q(X, Z)`, `R(Y, Z)`, `X > Y`) and selects the one that maximizes an information gain metric, often referred to as **FOIL's Gain**. This gain function is designed to measure how much a literal improves the rule by covering more positive examples and fewer negative examples. It's an adaptation of the information gain used in decision tree learning, but extended for first-order logic.
*   **Termination**: The refinement process continues until the rule covers only positive examples (or a predefined purity threshold is met) and/or no further literal significantly improves the rule's quality.

Once a rule is learned, all positive examples covered by it are removed from the training set, and the process repeats to learn the next rule until all (or most) positive examples are covered.

#### 3. First-Order Rules vs. Propositional Rules
The primary difference between first-order rules (as learned by FOIL) and propositional rules (like those from a `DecisionTreeClassifier`) lies in their expressive power and the types of relationships they can represent:

*   **Propositional Rules**: These rules operate on a fixed set of attributes (features) for each instance. They express conditions based on the values of these attributes. For example, a propositional rule might be: `IF 'petal length (cm)' <= 2.45 THEN class = 0`. Each condition refers to an attribute of a single, independent instance. They cannot directly express relationships between different objects or variable bindings.

*   **First-Order Rules**: These rules use variables, predicates, and quantifiers, allowing them to express complex relationships between multiple entities. For example, a first-order rule might be: `Grandparent(X, Y) :- Parent(X, Z) AND Parent(Z, Y)`. Here, `X`, `Y`, and `Z` are variables, and `Parent` and `Grandparent` are predicates. Such rules can represent properties of and relations between objects, which is crucial for relational learning tasks. This is a fundamental difference as propositional rules can only reason about the properties of a single entity at a time, while first-order rules can reason about networks of entities and their interactions.

#### 4. Application in Relational Domains
FOIL is particularly well-suited for relational domains because:

*   **Structured Data**: Data in relational domains is often stored across multiple tables (e.g., in a relational database), with foreign keys defining relationships between entities. A propositional learner would typically require flattening this data into a single, large table, which can lead to information loss, increased dimensionality, and difficulties in representing complex relationships.
*   **Relationships as First-Class Citizens**: FOIL can directly learn rules that involve these relationships. For instance, in a biological dataset, FOIL could learn rules about how protein interactions (relationships) affect disease outcomes, rather than just learning from static attributes of individual proteins.
*   **Expressiveness**: The ability of first-order logic to handle variables and predicates makes it naturally expressive for representing structured knowledge, making FOIL effective for tasks like learning drug interactions, predicting social network links, or understanding chemical structures.

#### 5. Challenges and Complexities
Implementing FOIL is significantly more challenging than implementing propositional rule learners like Decision Trees for several reasons:

*   **Computational Complexity**: Searching for optimal literals in a first-order space is much more complex than in a propositional space due to the need to consider variable bindings, unification, and a potentially vast number of possible predicates and variables.
*   **Lack of Standard Libraries**: Unlike propositional learning algorithms (e.g., `sklearn.tree.DecisionTreeClassifier`), there are no direct, widely available, and optimized implementations of FOIL in standard Python machine learning libraries like Scikit-learn. Implementations typically require deep understanding of logic programming and relational database concepts.
*   **Data Representation**: Preparing data for FOIL involves representing it in a way that aligns with first-order logic, often requiring a logical database or specialized data structures, rather than simple DataFrames.
*   **Interpretability**: While first-order rules are very expressive, their interpretation can be more complex for humans than simple propositional rules, especially as rules grow in length and complexity.

## Final Task

### Subtask:
Summarize the entire process, present the generated propositional classification rules, and reiterate the conceptual understanding of the FOIL algorithm and its relevance in machine learning, explaining its unique approach to learning relational knowledge.

## Summary:

### Data Analysis Key Findings
*   The Iris dataset was successfully loaded, comprising 150 instances with four numerical features ('sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)') and a target variable (three Iris species). No missing values were found.
*   The dataset was preprocessed by separating features and target, then splitting into training (120 samples) and testing (30 samples) sets using an 80/20 ratio.
*   Propositional classification rules were generated using a `DecisionTreeClassifier` (with `max_depth=4`). These rules primarily utilize `petal length (cm)` and `petal width (cm)` to classify the Iris species. The generated rules are as follows:
    ```
    |--- petal length (cm) <= 2.45
    |   |--- class: 0
    |--- petal length (cm) >  2.45
    |   |--- petal length (cm) <= 4.75
    |   |   |--- petal width (cm) <= 1.65
    |   |   |   |--- class: 1
    |   |   |--- petal width (cm) >  1.65
    |   |   |   |--- class: 2
    |   |--- petal length (cm) >  4.75
    |   |   |--- petal width (cm) <= 1.75
    |   |   |   |--- petal length (cm) <= 4.95
    |   |   |   |   |--- class: 1
    |   |   |   |--- petal length (cm) >  4.95
    |   |   |   |   |--- class: 2
    |   |   |--- petal width (cm) >  1.75
    |   |   |   |--- petal length (cm) <= 4.85
    |   |   |   |   |--- class: 2
    |   |   |   |--- petal length (cm) >  4.85
    |   |   |   |   |--- class: 2
    ```
*   A comprehensive conceptual explanation of the FOIL (First-Order Inductive Learner) algorithm was provided. It highlighted FOIL's greedy, top-down rule induction process, its ability to learn first-order logical rules involving variables and predicates, and its distinct advantages over propositional rule learners for capturing complex relationships within relational datasets.

### Insights or Next Steps
*   The `DecisionTreeClassifier` effectively generated clear and interpretable propositional rules for the Iris dataset, primarily based on `petal length` and `petal width`, indicating these features are highly discriminative for species classification.
*   While propositional rule induction is suitable for flat, attribute-value data like the Iris dataset, the conceptual understanding of FOIL underscores the necessity of first-order logic for modeling and learning from complex, relational data where interactions and relationships between entities are paramount.
"""