# -*- coding: utf-8 -*-
"""FOIL-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dot-h-wd-YMlT0XmTdXGlRjFfUVmgiv6
"""



"""# Task
Implement and evaluate simplified versions of example-based rule learning algorithms (like RIPPER or CN2) and the FOIL algorithm using a publicly available classification dataset.

## Load Public Dataset

### Subtask:
Load a suitable publicly available dataset for classification tasks, such as the Iris or Titanic dataset. This step will prepare the data for subsequent rule learning. If a dataset is not specified, I will default to a well-known public dataset.

**Reasoning**:
The subtask requires loading the Iris dataset, converting it into a Pandas DataFrame, and displaying its basic information. I will import necessary libraries, load the dataset, create the DataFrame with features and target, and then show the head and info of the DataFrame.
"""

import pandas as pd
from sklearn.datasets import load_iris

# 1. & 2. Load the Iris dataset
iris = load_iris()

# 3. Create a Pandas DataFrame from the dataset's features
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

# 4. Add the target variable (species) as a new column
df['species'] = iris.target
df['species'] = df['species'].map({i: name for i, name in enumerate(iris.target_names)})

# 5. Display the first 5 rows of the DataFrame
print("First 5 rows of the Iris DataFrame:")
print(df.head())

print("\n")

# 6. Print the information about the DataFrame
print("Information about the Iris DataFrame:")
df.info()

"""## Data Preprocessing

### Subtask:
Perform necessary data preprocessing steps, including handling missing values, encoding categorical features (if any), and splitting the dataset into training and testing sets. Rule induction algorithms often benefit from discretized numerical features, so this step might include discretization as well.

**Reasoning**:
First, I will separate the features (X) and the target variable (y) from the `df` DataFrame as per the instructions. 'species' is the target variable.
"""

X = df.drop('species', axis=1)
y = df['species']

print("Features (X) head:")
print(X.head())
print("\nTarget (y) head:")
print(y.head())

"""**Reasoning**:
Now that features and target are separated, I will discretize the numerical features in `X` using `KBinsDiscretizer` as specified in the instructions. This will convert continuous numerical data into discrete bins, which is often beneficial for rule induction algorithms.


"""

from sklearn.preprocessing import KBinsDiscretizer

# Initialize KBinsDiscretizer with 4 bins and 'ordinal' strategy
discretizer = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform', subsample=None, random_state=42)

# Fit and transform the features
X_discretized = discretizer.fit_transform(X)

# Convert the discretized features back to a DataFrame with original column names
X_discretized = pd.DataFrame(X_discretized, columns=X.columns)

print("First 5 rows of Discretized Features (X_discretized):")
print(X_discretized.head())

"""**Reasoning**:
I will split the discretized features (`X_discretized`) and the target variable (`y`) into training and testing sets using `train_test_split` to prepare the data for model training, as specified in the instructions.


"""

from sklearn.model_selection import train_test_split

# Split the preprocessed dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_discretized, y, test_size=0.25, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

"""## Implement Simplified Rule Learner (e.g., RIPPER/CN2)

### Subtask:
Develop a custom Python method that implements the core logic of an example-based rule learning algorithm like RIPPER or CN2. This will involve generating classification rules from the preprocessed training data.

**Reasoning**:
The first step in implementing the rule learner is to define the `SimplifiedRuleLearner` class and its `__init__` method. This will set up the basic structure of the algorithm and allow for initialization of parameters like minimum rule coverage and maximum conditions per rule.
"""

import pandas as pd
import numpy as np

class SimplifiedRuleLearner:
    def __init__(self, min_coverage=1, max_conditions=3):
        """
        Initializes the SimplifiedRuleLearner.

        Args:
            min_coverage (int): Minimum number of positive examples a rule must cover.
            max_conditions (int): Maximum number of conditions allowed in a single rule.
        """
        self.min_coverage = min_coverage
        self.max_conditions = max_conditions
        self.rules = [] # To store learned rules
        self.class_labels = None # To store unique class labels
        print("SimplifiedRuleLearner initialized with min_coverage=" + str(min_coverage) + " and max_conditions=" + str(max_conditions) + ".")

"""**Reasoning**:
Now that the `SimplifiedRuleLearner` class structure is initialized, I will implement the `fit` method as specified in the instructions. This method will take the training features (`X`) and target labels (`y`) as input, determine unique class labels, and serve as the entry point for the rule learning process.


"""

class SimplifiedRuleLearner:
    def __init__(self, min_coverage=1, max_conditions=3):
        self.min_coverage = min_coverage
        self.max_conditions = max_conditions
        self.rules = [] # To store learned rules
        self.class_labels = None # To store unique class labels

    def fit(self, X, y):
        """
        Learns classification rules from the training data.

        Args:
            X (pd.DataFrame): Training features.
            y (pd.Series): Training target labels.
        """
        self.class_labels = y.unique()
        print(f"Starting rule learning for classes: {self.class_labels}")
        # The core rule learning logic (cover and conquer) will be implemented here for each class
        # This is a placeholder for the next detailed steps.

print("Added fit method placeholder to SimplifiedRuleLearner class.")

"""**Reasoning**:
I will continue implementing the `fit` method by iterating through each unique class in the target variable `y` and initializing the set of positive examples for that class, which will be maintained as 'uncovered' examples in the 'cover and conquer' strategy.


"""

class SimplifiedRuleLearner:
    def __init__(self, min_coverage=1, max_conditions=3):
        self.min_coverage = min_coverage
        self.max_conditions = max_conditions
        self.rules = [] # To store learned rules
        self.class_labels = None # To store unique class labels

    def fit(self, X, y):
        """
        Learns classification rules from the training data.

        Args:
            X (pd.DataFrame): Training features.
            y (pd.Series): Training target labels.
        """
        self.class_labels = y.unique()
        print(f"Starting rule learning for classes: {self.class_labels}")

        # Prepare data for rule learning
        X_indexed = X.copy().reset_index(drop=True) # Ensure contiguous index
        y_indexed = y.copy().reset_index(drop=True)

        for target_class in self.class_labels:
            print(f"\nLearning rules for class: {target_class}")
            # Identify positive and negative examples for the current class
            positive_examples_indices = y_indexed[y_indexed == target_class].index
            negative_examples_indices = y_indexed[y_indexed != target_class].index

            # Maintain a set of currently 'uncovered' positive examples for the current class
            uncovered_positive_indices = set(positive_examples_indices)

            # Store rules for the current class temporarily
            class_rules = []

            # The core 'cover and conquer' loop
            while len(uncovered_positive_indices) > 0:
                # This is where the greedy search for the 'best' rule will be implemented
                # For now, we'll just break to prevent an infinite loop as rule generation isn't implemented yet
                print(f"  Remaining uncovered positive examples for {target_class}: {len(uncovered_positive_indices)}")
                break # Placeholder: implement rule generation and example removal here

            # After all rules for the class are learned, add them to the global rules list
            # self.rules.extend(class_rules) # This will be uncommented later

        print("Fit method partially implemented. Next step will focus on rule generation.")

"""**Reasoning**:
I will now implement the core 'cover and conquer' logic within the `fit` method. This involves iteratively building rules by greedily adding conditions that best cover the remaining positive examples for the target class while minimizing negative coverage, and then removing the covered examples, as specified in the instructions.


"""

import pandas as pd
import numpy as np

class SimplifiedRuleLearner:
    def __init__(self, min_coverage=1, max_conditions=3):
        self.min_coverage = min_coverage
        self.max_conditions = max_conditions
        self.rules = [] # To store learned rules
        self.class_labels = None # To store unique class labels

    def fit(self, X, y):
        """
        Learns classification rules from the training data.

        Args:
            X (pd.DataFrame): Training features.
            y (pd.Series): Training target labels.
        """
        self.class_labels = y.unique()
        print(f"Starting rule learning for classes: {self.class_labels}")

        # Prepare data for rule learning
        X_indexed = X.copy().reset_index(drop=True)
        y_indexed = y.copy().reset_index(drop=True)

        for target_class in self.class_labels:
            print(f"\nLearning rules for class: {target_class}")
            # Identify positive and negative examples for the current class
            positive_examples_indices = y_indexed[y_indexed == target_class].index
            negative_examples_indices = y_indexed[y_indexed != target_class].index

            # Maintain a set of currently 'uncovered' positive examples for the current class
            uncovered_positive_indices = set(positive_examples_indices)

            # Store rules for the current class temporarily
            class_rules = []

            # The core 'cover and conquer' loop
            while len(uncovered_positive_indices) > 0:
                current_rule_conditions = []
                best_rule_purity = -1.0 # Purity metric for the rule being built
                rule_covered_indices_at_step = set(range(len(X_indexed))) # Start with all indices

                # Greedily search for the 'best' rule by adding conditions
                for _ in range(self.max_conditions):
                    best_condition_for_step = None
                    max_condition_purity = -1.0 # Purity for adding this specific condition

                    # Find candidate conditions: all unique (feature, value) pairs not yet in current_rule_conditions
                    candidate_conditions = []
                    for col in X_indexed.columns:
                        # Ensure no duplicate features in a rule (a simplification for this rule learner)
                        if any(cond['feature'] == col for cond in current_rule_conditions):
                            continue
                        for val in X_indexed[col].unique():
                            candidate_conditions.append({'feature': col, 'value': val})

                    if not candidate_conditions: # No more conditions to add
                        break

                    for cond in candidate_conditions:
                        temp_conditions = current_rule_conditions + [cond]

                        # Evaluate the effect of these temp_conditions
                        temp_mask = pd.Series([True] * len(X_indexed))
                        for tc in temp_conditions:
                            temp_mask = temp_mask & (X_indexed[tc['feature']] == tc['value'])

                        temp_covered_indices = X_indexed[temp_mask].index

                        pos_covered_by_temp = len(set(temp_covered_indices) & uncovered_positive_indices)
                        neg_covered_by_temp = len(set(temp_covered_indices) & set(negative_examples_indices))

                        # Use a simple purity metric: (pos - neg) for simplicity (can be pos / (pos+neg))
                        # Prioritize rules that cover positive examples without covering negatives
                        purity = (pos_covered_by_temp - neg_covered_by_temp) if (pos_covered_by_temp > 0) else -1.0

                        if purity > max_condition_purity:
                            max_condition_purity = purity
                            best_condition_for_step = cond

                    if best_condition_for_step and max_condition_purity > -1.0: # A good condition was found
                        current_rule_conditions.append(best_condition_for_step)
                        # Update the set of covered indices by the partial rule
                        rule_mask = pd.Series([True] * len(X_indexed))
                        for cond in current_rule_conditions:
                            rule_mask = rule_mask & (X_indexed[cond['feature']] == cond['value'])
                        rule_covered_indices_at_step = set(X_indexed[rule_mask].index)

                        # Update purity of the current rule (not just the last added condition)
                        current_pos_covered = len(rule_covered_indices_at_step & uncovered_positive_indices)
                        current_neg_covered = len(rule_covered_indices_at_step & set(negative_examples_indices))
                        best_rule_purity = (current_pos_covered - current_neg_covered) if current_pos_covered > 0 else -1.0

                        # If adding this condition made the rule worse or no longer covers enough positives,
                        # we might want to backtrack or stop. For simplicity, we proceed unless max_conditions is reached.

                    else:
                        # No suitable condition found to extend the rule meaningfully
                        break

                # After building a rule (potentially empty or partial)
                if current_rule_conditions:
                    rule_mask = pd.Series([True] * len(X_indexed))
                    for cond in current_rule_conditions:
                        rule_mask = rule_mask & (X_indexed[cond['feature']] == cond['value'])

                    final_covered_indices = X_indexed[rule_mask].index
                    final_pos_covered = len(set(final_covered_indices) & uncovered_positive_indices)
                    final_neg_covered = len(set(final_covered_indices) & set(negative_examples_indices))

                    # Check if the rule is valid (covers enough positives, not too many negatives, and has positive purity)
                    # A very simple stopping criteria: covers at least min_coverage positives and has positive purity.
                    if final_pos_covered >= self.min_coverage and (final_pos_covered - final_neg_covered) > 0:
                        class_rules.append({'conditions': current_rule_conditions, 'prediction': target_class})
                        uncovered_positive_indices = uncovered_positive_indices - set(final_covered_indices) # Remove covered positives
                        print(f"  Learned rule for {target_class}: {current_rule_conditions}, covers {final_pos_covered} positives, {final_neg_covered} negatives. Remaining uncovered: {len(uncovered_positive_indices)}")
                    else:
                        print(f"  Discarded rule for {target_class} (conditions: {current_rule_conditions}) due to low coverage ({final_pos_covered}) or insufficient purity (P:{final_pos_covered}, N:{final_neg_covered}). Stopping rule search for this class.")
                        break # Stop searching for more rules for this class if the last attempt was not good
                else:
                    print(f"  Could not find any suitable rule for {target_class}. Stopping rule search for this class.")
                    break # Cannot find any rule for this class, exit loop

            self.rules.extend(class_rules)
            print(f"Finished learning rules for class: {target_class}. Total rules for this class: {len(class_rules)}")

        print("\nFit method fully implemented with simplified rule generation.")

print("SimplifiedRuleLearner class updated with full 'fit' method implementation.")

"""**Reasoning**:
Now that the `fit` method is fully implemented, I will implement the `predict` method. This method will take new features (`X`) as input, apply the learned rules, and predict the class labels. A simple conflict resolution strategy will be used: the first rule that matches an instance will determine its class.


"""

class SimplifiedRuleLearner:
    def __init__(self, min_coverage=1, max_conditions=3):
        self.min_coverage = min_coverage
        self.max_conditions = max_conditions
        self.rules = [] # To store learned rules
        self.class_labels = None # To store unique class labels

    def fit(self, X, y):
        """
        Learns classification rules from the training data.

        Args:
            X (pd.DataFrame): Training features.
            y (pd.Series): Training target labels.
        """
        self.class_labels = y.unique()
        # print(f"Starting rule learning for classes: {self.class_labels}") # Commented out to avoid redundant print in this cell

        X_indexed = X.copy().reset_index(drop=True)
        y_indexed = y.copy().reset_index(drop=True)

        for target_class in self.class_labels:
            # print(f"\nLearning rules for class: {target_class}") # Commented out
            positive_examples_indices = y_indexed[y_indexed == target_class].index
            negative_examples_indices = y_indexed[y_indexed != target_class].index

            uncovered_positive_indices = set(positive_examples_indices)

            class_rules = []

            while len(uncovered_positive_indices) > 0:
                current_rule_conditions = []
                best_rule_purity = -1.0
                rule_covered_indices_at_step = set(range(len(X_indexed)))

                for _ in range(self.max_conditions):
                    best_condition_for_step = None
                    max_condition_purity = -1.0

                    candidate_conditions = []
                    for col in X_indexed.columns:
                        if any(cond['feature'] == col for cond in current_rule_conditions):
                            continue
                        for val in X_indexed[col].unique():
                            candidate_conditions.append({'feature': col, 'value': val})

                    if not candidate_conditions:
                        break

                    for cond in candidate_conditions:
                        temp_conditions = current_rule_conditions + [cond]

                        temp_mask = pd.Series([True] * len(X_indexed))
                        for tc in temp_conditions:
                            temp_mask = temp_mask & (X_indexed[tc['feature']] == tc['value'])

                        temp_covered_indices = X_indexed[temp_mask].index

                        pos_covered_by_temp = len(set(temp_covered_indices) & uncovered_positive_indices)
                        neg_covered_by_temp = len(set(temp_covered_indices) & set(negative_examples_indices))

                        purity = (pos_covered_by_temp - neg_covered_by_temp) if (pos_covered_by_temp > 0) else -1.0

                        if purity > max_condition_purity:
                            max_condition_purity = purity
                            best_condition_for_step = cond

                    if best_condition_for_step and max_condition_purity > -1.0:
                        current_rule_conditions.append(best_condition_for_step)
                        rule_mask = pd.Series([True] * len(X_indexed))
                        for cond in current_rule_conditions:
                            rule_mask = rule_mask & (X_indexed[cond['feature']] == cond['value'])
                        rule_covered_indices_at_step = set(X_indexed[rule_mask].index)

                        current_pos_covered = len(rule_covered_indices_at_step & uncovered_positive_indices)
                        current_neg_covered = len(rule_covered_indices_at_step & set(negative_examples_indices))
                        best_rule_purity = (current_pos_covered - current_neg_covered) if current_pos_covered > 0 else -1.0
                    else:
                        break

                if current_rule_conditions:
                    rule_mask = pd.Series([True] * len(X_indexed))
                    for cond in current_rule_conditions:
                        rule_mask = rule_mask & (X_indexed[cond['feature']] == cond['value'])

                    final_covered_indices = X_indexed[rule_mask].index
                    final_pos_covered = len(set(final_covered_indices) & uncovered_positive_indices)
                    final_neg_covered = len(set(final_covered_indices) & set(negative_examples_indices))

                    if final_pos_covered >= self.min_coverage and (final_pos_covered - final_neg_covered) > 0:
                        class_rules.append({'conditions': current_rule_conditions, 'prediction': target_class})
                        uncovered_positive_indices = uncovered_positive_indices - set(final_covered_indices)
                        # print(f"  Learned rule for {target_class}: {current_rule_conditions}, covers {final_pos_covered} positives, {final_neg_covered} negatives. Remaining uncovered: {len(uncovered_positive_indices)}") # Commented out
                    else:
                        # print(f"  Discarded rule for {target_class} (conditions: {current_rule_conditions}) due to low coverage ({final_pos_covered}) or insufficient purity (P:{final_pos_covered}, N:{final_neg_covered}). Stopping rule search for this class.") # Commented out
                        break
                else:
                    # print(f"  Could not find any suitable rule for {target_class}. Stopping rule search for this class.") # Commented out
                    break

            self.rules.extend(class_rules)
            # print(f"Finished learning rules for class: {target_class}. Total rules for this class: {len(class_rules)}") # Commented out

        print("Fit method fully implemented and rules learned.") # Updated print message

    def predict(self, X):
        """
        Predicts class labels for new instances based on learned rules.

        Args:
            X (pd.DataFrame): Features for which to make predictions.

        Returns:
            pd.Series: Predicted class labels.
        """
        predictions = []
        for index, row in X.iterrows():
            predicted_class = None
            # Apply rules in the order they were learned (simple conflict resolution: first rule that fires wins)
            for rule in self.rules:
                match = True
                for condition in rule['conditions']:
                    feature = condition['feature']
                    value = condition['value']
                    if row[feature] != value:
                        match = False
                        break
                if match:
                    predicted_class = rule['prediction']
                    break # First rule that fires wins

            # If no rule fires, assign the most frequent class from training data (default prediction)
            if predicted_class is None:
                # This is a simplification. A more robust approach might be to assign
                # a 'default' class based on the overall majority class or a specific tie-breaking rule.
                # For now, we'll assign 'Unknown' or handle as needed.
                # For this dataset, we can assume rules will cover most cases or
                # predict based on the training set's overall majority class if needed.
                # For simplicity, if no rule matches, we will return None for now.
                # In a real scenario, this would be a specific strategy (e.g., majority class, reject).
                predicted_class = 'No Rule Matched'

            predictions.append(predicted_class)

        print(f"Predictions made for {len(X)} instances using {len(self.rules)} rules.")
        return pd.Series(predictions, index=X.index)

print("SimplifiedRuleLearner class updated with full 'fit' and 'predict' methods.")

"""## Implement Simplified FOIL Algorithm

### Subtask:
Develop a custom Python method to implement the core logic of the First-Order Inductive Learner (FOIL) algorithm. This method will learn first-order rules for predicting the target variable, focusing on concepts like finding the best literal and covering examples. This will be a conceptual implementation to demonstrate the algorithm's principles.

**Reasoning**:
I will define the `SimplifiedFOIL` class and implement its `__init__` method, initializing `max_conditions`, `min_gain`, and an empty list for `rules` as specified in the instructions.
"""

import pandas as pd
import numpy as np

class SimplifiedFOIL:
    def __init__(self, max_conditions=3, min_gain=0.1):
        """
        Initializes the SimplifiedFOIL algorithm.

        Args:
            max_conditions (int): Maximum number of literals (conditions) allowed in a single rule.
            min_gain (float): Minimum FOIL gain required to add a literal to a rule.
        """
        self.max_conditions = max_conditions
        self.min_gain = min_gain
        self.rules = [] # To store learned rules
        self.class_labels = None # To store unique class labels
        print("SimplifiedFOIL initialized with max_conditions=" + str(max_conditions) + " and min_gain=" + str(min_gain) + ".")

"""**Reasoning**:
Now that the `SimplifiedFOIL` class structure is initialized, I will implement the `fit` method. This method will prepare the data for rule learning and iterate through each target class to begin the FOIL rule induction process.


"""

class SimplifiedFOIL:
    def __init__(self, max_conditions=3, min_gain=0.1):
        self.max_conditions = max_conditions
        self.min_gain = min_gain
        self.rules = [] # To store learned rules
        self.class_labels = None # To store unique class labels

    def fit(self, X, y):
        """
        Learns classification rules from the training data using a simplified FOIL approach.

        Args:
            X (pd.DataFrame): Training features.
            y (pd.Series): Training target labels.
        """
        self.class_labels = y.unique()
        print(f"Starting FOIL rule learning for classes: {self.class_labels}")

        # Prepare data for rule learning (ensure consistent indexing)
        X_indexed = X.copy().reset_index(drop=True)
        y_indexed = y.copy().reset_index(drop=True)

        for target_class in self.class_labels:
            print(f"\nLearning FOIL rules for class: {target_class}")
            # Identify positive and negative examples for the current class
            # In FOIL, we typically learn rules for one class at a time against all others.
            positive_examples_indices = y_indexed[y_indexed == target_class].index
            negative_examples_indices = y_indexed[y_indexed != target_class].index

            # Maintain a set of currently 'uncovered' positive examples for the current class
            uncovered_positive_indices = set(positive_examples_indices)

            # Store rules for the current class temporarily
            class_rules = []

            # The core FOIL 'cover and conquer' loop will go here
            while len(uncovered_positive_indices) > 0:
                # This is where the greedy search for the 'best' literal and rule construction will be implemented.
                # For now, we'll just break to prevent an infinite loop as rule generation isn't implemented yet.
                print(f"  Remaining uncovered positive examples for {target_class}: {len(uncovered_positive_indices)}")
                break # Placeholder: implement rule generation and example removal here

            # After all rules for the class are learned, add them to the global rules list
            # self.rules.extend(class_rules) # This will be uncommented later

        print("FOIL fit method partially implemented. Next step will focus on literal generation and FOIL gain.")

"""**Reasoning**:
I will implement the core 'cover and conquer' logic within the `fit` method for the `SimplifiedFOIL` class, including a helper method to calculate FOIL gain. This involves iteratively building rules by greedily adding conditions that maximize FOIL gain, covering positive examples, and minimizing negative coverage, as specified in the instructions.


"""

import pandas as pd
import numpy as np

class SimplifiedFOIL:
    def __init__(self, max_conditions=3, min_gain=0.1):
        self.max_conditions = max_conditions
        self.min_gain = min_gain
        self.rules = [] # To store learned rules
        self.class_labels = None # To store unique class labels

    def _calculate_foil_gain(self, p0, n0, p1, n1):
        """
        Calculates the FOIL gain for adding a literal.
        p0: positive examples covered by current rule (before adding literal)
        n0: negative examples covered by current rule (before adding literal)
        p1: positive examples covered by current rule + new literal
        n1: negative examples covered by current rule + new literal
        """
        def _info(p, n):
            if p == 0: return 0.0 # If no positive examples, information is 0 (to avoid log(0))
            if p + n == 0: return 0.0 # Avoid division by zero
            return np.log2(p / (p + n))

        # If the new literal covers no positive examples, it cannot contribute to gain.
        if p1 == 0:
            return -float('inf') # A very low gain, making it unlikely to be chosen

        info_p1_n1 = _info(p1, n1)
        info_p0_n0 = _info(p0, n0)

        gain = p1 * (info_p1_n1 - info_p0_n0)
        return gain

    def fit(self, X, y):
        """
        Learns classification rules from the training data using a simplified FOIL approach.

        Args:
            X (pd.DataFrame): Training features.
            y (pd.Series): Training target labels.
        """
        self.class_labels = y.unique()
        print(f"Starting FOIL rule learning for classes: {self.class_labels}")

        # Prepare data for rule learning (ensure consistent indexing)
        X_indexed = X.copy().reset_index(drop=True)
        y_indexed = y.copy().reset_index(drop=True)

        for target_class in self.class_labels:
            print(f"\nLearning FOIL rules for class: {target_class}")
            # Identify positive and negative examples for the current class
            positive_examples_indices = y_indexed[y_indexed == target_class].index
            negative_examples_indices = y_indexed[y_indexed != target_class].index

            # Maintain a set of currently 'uncovered' positive examples for the current class
            uncovered_positive_indices = set(positive_examples_indices)

            class_rules = []

            # The core FOIL 'cover and conquer' loop
            while len(uncovered_positive_indices) > 0:
                current_rule_conditions = []

                # The mask for examples covered by the current partial rule
                # Initially, this covers all examples we are considering (uncovered positives + all negatives).
                current_rule_match_mask = pd.Series([True] * len(X_indexed), index=X_indexed.index)

                # Greedily search for the 'best' literal to add
                for _ in range(self.max_conditions): # Grow rule up to max_conditions literals
                    best_literal_for_step = None
                    max_gain_for_step = -float('inf')

                    # Generate candidate literals: (feature, value) pairs not yet in current_rule_conditions
                    candidate_literals = []
                    for col in X_indexed.columns:
                        # Ensure no duplicate features in a rule for simplicity
                        if any(cond['feature'] == col for cond in current_rule_conditions):
                            continue
                        for val in X_indexed[col].unique():
                            candidate_literals.append({'feature': col, 'value': val})

                    if not candidate_literals: # No more candidate literals to add
                        break

                    # Calculate p0 and n0 for the current partial rule (before adding a new literal)
                    # These are examples from the original set that currently match the rule
                    p0_current_rule = len(set(X_indexed[current_rule_match_mask].index) & uncovered_positive_indices)
                    n0_current_rule = len(set(X_indexed[current_rule_match_mask].index) & set(negative_examples_indices))

                    # If the current rule already covers no positive examples, cannot extend it beneficially
                    if p0_current_rule == 0:
                        break

                    for literal in candidate_literals:
                        # Create a temporary mask with the current rule conditions + candidate literal
                        temp_match_mask = current_rule_match_mask & (X_indexed[literal['feature']] == literal['value'])
                        temp_covered_indices = X_indexed[temp_match_mask].index

                        # Count positives and negatives covered by the extended rule
                        p1 = len(set(temp_covered_indices) & uncovered_positive_indices)
                        n1 = len(set(temp_covered_indices) & set(negative_examples_indices))

                        # Calculate FOIL gain for adding this literal
                        gain = self._calculate_foil_gain(p0_current_rule, n0_current_rule, p1, n1)

                        if gain > max_gain_for_step:
                            max_gain_for_step = gain
                            best_literal_for_step = literal

                    # If a good literal was found and its gain is above threshold, add it
                    if best_literal_for_step and max_gain_for_step > self.min_gain:
                        current_rule_conditions.append(best_literal_for_step)
                        # Update the current_rule_match_mask to include the new literal
                        current_rule_match_mask = current_rule_match_mask & (X_indexed[best_literal_for_step['feature']] == best_literal_for_step['value'])
                        print(f"    Added literal: {best_literal_for_step}, current gain: {max_gain_for_step:.4f}")
                    else:
                        break # Stop growing the rule if no beneficial literal can be added or gain is too low

                # After building a rule (potentially empty or partial), check its validity and add it
                if current_rule_conditions: # A rule was successfully built
                    final_covered_indices = X_indexed[current_rule_match_mask].index
                    final_pos_covered = len(set(final_covered_indices) & uncovered_positive_indices)
                    final_neg_covered = len(set(final_covered_indices) & set(negative_examples_indices))

                    # A rule must cover at least one positive example from the uncovered set
                    if final_pos_covered > 0:
                        class_rules.append({'conditions': current_rule_conditions, 'prediction': target_class})
                        # Remove covered positive examples from the uncovered set
                        uncovered_positive_indices = uncovered_positive_indices - set(final_covered_indices)
                        print(f"  Learned FOIL rule for {target_class}: {current_rule_conditions}, covers {final_pos_covered} positives, {final_neg_covered} negatives. Remaining uncovered: {len(uncovered_positive_indices)}")
                    else:
                        print(f"  Discarded rule for {target_class} (conditions: {current_rule_conditions}) due to low positive coverage (0). Stopping rule search for this class.")
                        break # No more rules can be found for this class that cover positives
                else:
                    print(f"  Could not find any suitable FOIL rule for {target_class}. Stopping rule search for this class.")
                    break # Cannot find any rule for this class, exit loop

            self.rules.extend(class_rules)
            print(f"Finished learning FOIL rules for class: {target_class}. Total rules for this class: {len(class_rules)}")

        print("\nFOIL fit method fully implemented with simplified FOIL gain.")

"""**Reasoning**:
Now that the `fit` method of `SimplifiedFOIL` is fully implemented, I will implement the `predict` method. This method will take new features (`X`) as input, apply the learned FOIL rules, and predict the class labels for each instance, using a first-match conflict resolution strategy.


"""

class SimplifiedFOIL:
    def __init__(self, max_conditions=3, min_gain=0.1):
        self.max_conditions = max_conditions
        self.min_gain = min_gain
        self.rules = [] # To store learned rules
        self.class_labels = None # To store unique class labels

    def _calculate_foil_gain(self, p0, n0, p1, n1):
        # (Omitted for brevity as it's already implemented and not changed in this step)
        def _info(p, n):
            if p == 0: return 0.0
            if p + n == 0: return 0.0
            return np.log2(p / (p + n))

        if p1 == 0:
            return -float('inf')

        info_p1_n1 = _info(p1, n1)
        info_p0_n0 = _info(p0, n0)

        gain = p1 * (info_p1_n1 - info_p0_n0)
        return gain

    def fit(self, X, y):
        # (Omitted for brevity as it's already implemented and not changed in this step)
        self.class_labels = y.unique()
        # print(f"Starting FOIL rule learning for classes: {self.class_labels}") # Commented out for cleaner output

        X_indexed = X.copy().reset_index(drop=True)
        y_indexed = y.copy().reset_index(drop=True)

        for target_class in self.class_labels:
            # print(f"\nLearning FOIL rules for class: {target_class}") # Commented out
            positive_examples_indices = y_indexed[y_indexed == target_class].index
            negative_examples_indices = y_indexed[y_indexed != target_class].index

            uncovered_positive_indices = set(positive_examples_indices)

            class_rules = []

            while len(uncovered_positive_indices) > 0:
                current_rule_conditions = []
                current_rule_match_mask = pd.Series([True] * len(X_indexed), index=X_indexed.index)

                for _ in range(self.max_conditions):
                    best_literal_for_step = None
                    max_gain_for_step = -float('inf')

                    candidate_literals = []
                    for col in X_indexed.columns:
                        if any(cond['feature'] == col for cond in current_rule_conditions):
                            continue
                        for val in X_indexed[col].unique():
                            candidate_literals.append({'feature': col, 'value': val})

                    if not candidate_literals:
                        break

                    p0_current_rule = len(set(X_indexed[current_rule_match_mask].index) & uncovered_positive_indices)
                    n0_current_rule = len(set(X_indexed[current_rule_match_mask].index) & set(negative_examples_indices))

                    if p0_current_rule == 0:
                        break

                    for literal in candidate_literals:
                        temp_match_mask = current_rule_match_mask & (X_indexed[literal['feature']] == literal['value'])
                        temp_covered_indices = X_indexed[temp_match_mask].index

                        p1 = len(set(temp_covered_indices) & uncovered_positive_indices)
                        n1 = len(set(temp_covered_indices) & set(negative_examples_indices))

                        gain = self._calculate_foil_gain(p0_current_rule, n0_current_rule, p1, n1)

                        if gain > max_gain_for_step:
                            max_gain_for_step = gain
                            best_literal_for_step = literal

                    if best_literal_for_step and max_gain_for_step > self.min_gain:
                        current_rule_conditions.append(best_literal_for_step)
                        current_rule_match_mask = current_rule_match_mask & (X_indexed[best_literal_for_step['feature']] == best_literal_for_step['value'])
                        # print(f"    Added literal: {best_literal_for_step}, current gain: {max_gain_for_step:.4f}") # Commented out
                    else:
                        break

                if current_rule_conditions:
                    final_covered_indices = X_indexed[current_rule_match_mask].index
                    final_pos_covered = len(set(final_covered_indices) & uncovered_positive_indices)
                    final_neg_covered = len(set(final_covered_indices) & set(negative_examples_indices))

                    if final_pos_covered > 0:
                        class_rules.append({'conditions': current_rule_conditions, 'prediction': target_class})
                        uncovered_positive_indices = uncovered_positive_indices - set(final_covered_indices)
                        # print(f"  Learned FOIL rule for {target_class}: {current_rule_conditions}, covers {final_pos_covered} positives, {final_neg_covered} negatives. Remaining uncovered: {len(uncovered_positive_indices)}") # Commented out
                    else:
                        # print(f"  Discarded rule for {target_class} (conditions: {current_rule_conditions}) due to low positive coverage (0). Stopping rule search for this class.") # Commented out
                        break
                else:
                    # print(f"  Could not find any suitable FOIL rule for {target_class}. Stopping rule search for this class.") # Commented out
                    break

            self.rules.extend(class_rules)
            # print(f"Finished learning FOIL rules for class: {target_class}. Total rules for this class: {len(class_rules)}") # Commented out

        print("FOIL fit method fully implemented and rules learned.") # Updated print message

    def predict(self, X):
        """
        Predicts class labels for new instances based on learned FOIL rules.

        Args:
            X (pd.DataFrame): Features for which to make predictions.

        Returns:
            pd.Series: Predicted class labels.
        """
        predictions = []
        for index, row in X.iterrows():
            predicted_class = None
            # Apply rules in the order they were learned (first rule that fires wins)
            for rule in self.rules:
                match = True
                for condition in rule['conditions']:
                    feature = condition['feature']
                    value = condition['value']
                    if row[feature] != value:
                        match = False
                        break
                if match:
                    predicted_class = rule['prediction']
                    break # First rule that fires wins

            # If no rule fires, assign the most frequent class from training data (default prediction)
            if predicted_class is None:
                # This is a simplification. A more robust approach might be to assign
                # a 'default' class based on the overall majority class or a specific tie-breaking rule.
                # For now, if no rule matches, we will return a placeholder 'No Rule Matched'.
                predicted_class = 'No Rule Matched'

            predictions.append(predicted_class)

        print(f"Predictions made for {len(X)} instances using {len(self.rules)} FOIL rules.")
        return pd.Series(predictions, index=X.index)

print("SimplifiedFOIL class updated with full 'fit' and 'predict' methods.")

"""## Apply and Evaluate Custom Algorithms

### Subtask:
Apply the custom-built rule learning (RIPPER/CN2) and FOIL algorithms to the preprocessed dataset. Evaluate the generated classification rules and first-order rules using appropriate metrics (e.g., accuracy, precision, recall) on the test set. Visualize the performance or properties of the learned rules if feasible.

**Reasoning**:
I will instantiate the `SimplifiedRuleLearner` and `SimplifiedFOIL` models, then train them on the `X_train` and `y_train` datasets as instructed.
"""

print("Instantiating and training SimplifiedRuleLearner...")
rule_learner_model = SimplifiedRuleLearner(min_coverage=1, max_conditions=3)
rule_learner_model.fit(X_train, y_train)

print("\nInstantiating and training SimplifiedFOIL...")
foil_model = SimplifiedFOIL(max_conditions=3, min_gain=0.1)
foil_model.fit(X_train, y_train)

print("Models instantiated and trained.")

"""**Reasoning**:
Now that both models are trained, I will use them to make predictions on the test set (`X_test`) as per the instructions.


"""

print("Making predictions with SimplifiedRuleLearner...")
y_pred_rule_learner = rule_learner_model.predict(X_test)

print("\nMaking predictions with SimplifiedFOIL...")
y_pred_foil = foil_model.predict(X_test)

print("Predictions generated for both models.")

"""**Reasoning**:
I will import the necessary metrics from `sklearn.metrics` and then calculate and print the accuracy, precision, recall, and F1-score for both the `SimplifiedRuleLearner` and `SimplifiedFOIL` predictions against the true labels, as specified in the instructions.


"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("\n--- Evaluation for SimplifiedRuleLearner ---")
# Calculate metrics for SimplifiedRuleLearner
# Handle 'No Rule Matched' by potentially ignoring or considering it an incorrect prediction
# For simplicity, we'll treat 'No Rule Matched' as an incorrect prediction during evaluation.

# Ensure y_test and y_pred_rule_learner have same length and index for direct comparison
# Filter out instances where no rule matched if needed, or replace with a default for evaluation

# Before calculating metrics, ensure y_test only contains values present in y_pred_rule_learner (or vice versa)
# For precision, recall, f1, we need to specify average since it's multi-class

# Filter out 'No Rule Matched' from predictions for metrics that require known classes
valid_indices_rule_learner = y_pred_rule_learner[y_pred_rule_learner != 'No Rule Matched'].index
y_test_filtered_rule_learner = y_test.loc[valid_indices_rule_learner]
y_pred_filtered_rule_learner = y_pred_rule_learner.loc[valid_indices_rule_learner]

# For accuracy, we can directly compare, treating 'No Rule Matched' as wrong
accuracy_rule_learner = accuracy_score(y_test, y_pred_rule_learner)
print(f"Accuracy: {accuracy_rule_learner:.4f}")

# For precision, recall, f1, use filtered data and specify 'weighted' average
if len(y_test_filtered_rule_learner) > 0:
    precision_rule_learner = precision_score(y_test_filtered_rule_learner, y_pred_filtered_rule_learner, average='weighted', zero_division=0)
    recall_rule_learner = recall_score(y_test_filtered_rule_learner, y_pred_filtered_rule_learner, average='weighted', zero_division=0)
    f1_rule_learner = f1_score(y_test_filtered_rule_learner, y_pred_filtered_rule_learner, average='weighted', zero_division=0)
    print(f"Precision (weighted): {precision_rule_learner:.4f}")
    print(f"Recall (weighted): {recall_rule_learner:.4f}")
    print(f"F1-Score (weighted): {f1_rule_learner:.4f}")
else:
    print("No valid predictions for precision, recall, F1-score (all were 'No Rule Matched').")

print("\n--- Evaluation for SimplifiedFOIL ---")
# Calculate metrics for SimplifiedFOIL
valid_indices_foil = y_pred_foil[y_pred_foil != 'No Rule Matched'].index
y_test_filtered_foil = y_test.loc[valid_indices_foil]
y_pred_filtered_foil = y_pred_foil.loc[valid_indices_foil]

accuracy_foil = accuracy_score(y_test, y_pred_foil)
print(f"Accuracy: {accuracy_foil:.4f}")

if len(y_test_filtered_foil) > 0:
    precision_foil = precision_score(y_test_filtered_foil, y_pred_filtered_foil, average='weighted', zero_division=0)
    recall_foil = recall_score(y_test_filtered_foil, y_pred_filtered_foil, average='weighted', zero_division=0)
    f1_foil = f1_score(y_test_filtered_foil, y_pred_filtered_foil, average='weighted', zero_division=0)
    print(f"Precision (weighted): {precision_foil:.4f}")
    print(f"Recall (weighted): {recall_foil:.4f}")
    print(f"F1-Score (weighted): {f1_foil:.4f}")
else:
    print("No valid predictions for precision, recall, F1-score (all were 'No Rule Matched').")

print("Evaluation complete.")

"""## Final Task

### Subtask:
Summarize the process, the implementations of the custom algorithms, and the evaluation results for both the example-based classification rules and the first-order rules learned by FOIL.

## Summary:

### Data Analysis Key Findings

*   The Iris dataset, comprising 150 entries with 4 numerical features and 3 target species, was utilized for this analysis. All features were discretized into 4 bins using `KBinsDiscretizer` and the dataset was split into training (112 instances) and testing (38 instances) sets.
*   A custom `SimplifiedRuleLearner` (example-based classification) was implemented using a "cover and conquer" strategy, generating rules for each class based on a simple purity metric. The model learned 15 rules from the training data.
*   A custom `SimplifiedFOIL` algorithm was developed, employing a "cover and conquer" strategy that greedily adds literals to rules based on maximizing FOIL gain. This model learned 12 first-order rules from the training data.
*   Both custom-built rule learning models were evaluated on the test set.
    *   The `SimplifiedRuleLearner` achieved an accuracy of 0.8684, with a weighted precision of 0.9543, weighted recall of 0.9429, and a weighted F1-score of 0.9434.
    *   The `SimplifiedFOIL` algorithm achieved an accuracy of 0.8684, with a weighted precision of 0.9071, weighted recall of 0.8684, and a weighted F1-score of 0.8604.
*   For the instances where rules were matched, the `SimplifiedRuleLearner` demonstrated slightly higher precision, recall, and F1-score compared to `SimplifiedFOIL` on this specific dataset, despite both achieving the same overall accuracy.

### Insights or Next Steps

*   The performance of both custom rule learners indicates their potential for classification. Further refinement of the rule generation and selection criteria (e.g., alternative purity metrics, rule pruning) could potentially enhance their performance and rule interpretability.
*   Investigate the "No Rule Matched" cases for both models. Understanding why certain instances are not covered by any rule can inform improvements in rule generation or necessitate a default classification strategy (e.g., majority class) for such instances.
"""